spring:

  datasource: 
    driver: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hotel_aulra_spring?createDatabaseIfNotExist=true
    username: ${USER_DB}
    password: ${PASS_DB}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
    

gg:
  jte:
    templateLocation: src/main/resources/templates
    templateSuffix: .jte
    developmentMode: true
  
  
    

