spring:

  datasource: 
    driver: org.sqlite.JDBC
    url: jdbc:sqlite:memory:myDb?cache=shared 
    username: sa
    password: sa
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

server:
  port: 8080
    

gg:
  jte:
    usePrecompiledTemplates: true
  
  
    

