spring:

  datasource: 
    driver: org.mariadb.jdbc.Driver
    url: ${HOSTNAME_DB}
    username: ${USER_DB}
    password: ${PASS_DB}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8081
    

gg:
  jte:
    developmentMode: false
    usePrecompiledTemplates: true
  
  
    

