spring:

  datasource: 
    driver: org.mariadb.jdbc.Driver
    url: ${HOSTNAME_DB}
    username: ${USER_DB}
    password: ${PASSWD_DB}
  
  redis:
    host: localhost
    port: 6379
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
    

gg:
  jte:
    templateLocation: src/main/resources/templates
    templateSuffix: .jte
    usePrecompiledTemplates: true
  
  
    

